services:
  db:
    image: postgres:14
    container_name: market_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-market_db}
    ports:
      - "5432:5432"  # 通常は不要
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: market_backend
    command: >
       bash -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/src:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-market_db}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: "True"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: market_frontend
    volumes:
      - ./frontend/src:/app
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - VUE_APP_API_BASE_URL=http://backend:8000

volumes:
  postgres_data: